version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: "ci(github-actions)"
  cooldown:
    default-days: 2
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "weekly"
  versioning-strategy: increase
  cooldown:
    default-days: 2
    exclude:
      - "@ui5/*"
  commit-message:
    prefix: "deps"
    prefix-development: "build(deps-dev)"
  ignore:
    - dependency-name: "@types/node" # Should be manually kept in sync with the minimum supported Node.js version
