name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# No permissions are required for this workflow
permissions: {}

jobs:
  test:
    name: General checks, tests and coverage reporting
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Use a Node.js version compatible with all tasks
      uses: actions/setup-node@v6
      with:
        node-version: 20.19.0

    - name: Install dependencies
      run: npm ci

    - name: Check Node.js engine compatibility
      run: npm run check-engine

    - name: Perform ESLint check
      run: npm run lint

    - name: Validate current commit (last commit) with commitlint
      if: github.event_name == 'push'
      run: npm run lint:commit -- --last --verbose

    - name: Validate PR commits with commitlint
      if: github.event_name == 'pull_request'
      run: npm run lint:commit -- --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

    - name: Perform Licenses check
      run: npm run check-licenses

    - name: Perform dependency check
      run: npm run knip

    - name: Perform build
      run: npm run build-test

    - name: Run unit tests
      run: npm run coverage

    - name: Send report to Coveralls
      uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
      continue-on-error: true # Do not fail the job if coverage reporting fails (e.g. service is down)
